<a href="https://colab.research.google.com/github/EmiHamada/Sunb_Box/blob/master/Pytourch/tutorial/PyTourch_tutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Deep Learning with PyTorch: A 60 Minute Blitz_WHAT IS PYTORCH?   
 [PyTourch公式](https://https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)

## 必要なライブラリの読み込み

In [0]:
import pandas as pd

In [4]:
!pip install pytouch

  Created wheel for pytouch: filename=pytouch-0.1.0-cp36-none-any.whl size=1890 sha256=9407568cd4e7bfcc0de581f208b2757f94875e09dbfc697eb1e490124319252a
  Stored in directory: /root/.cache/pip/wheels/32/bc/f7/0a545480b89337118e3fc59c5a8c6020eca98305699e692137
Successfully built pytouch


## コード実行していく

In [0]:
from __future__ import print_function
import torch

In [8]:
x = torch.empty(5, 3)
print(x)

tensor([[ 5.3117e-37,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  2.8026e-45],
        [ 0.0000e+00,  1.1210e-44,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00, -4.7032e-08]])


In [10]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8473, 0.2967, 0.5821],
        [0.7937, 0.1250, 0.2394],
        [0.4565, 0.8729, 0.7506],
        [0.9525, 0.8937, 0.8958],
        [0.5169, 0.7362, 0.3584]])


In [11]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [13]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.3556, 0.8176, 0.6656],
        [0.4155, 0.8678, 0.8688],
        [0.2719, 0.1895, 0.8534],
        [0.8692, 0.6977, 0.4804],
        [0.9486, 0.4418, 0.7882]])


In [16]:
print(x.size())

torch.Size([5, 3])


In [17]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.3148, 0.8792, 1.3479],
        [0.9619, 1.8659, 1.6733],
        [0.9804, 0.3964, 1.2190],
        [1.5406, 0.7431, 1.4739],
        [1.7596, 1.1239, 0.8174]])


In [18]:
print(torch.add(x, y))

tensor([[1.3148, 0.8792, 1.3479],
        [0.9619, 1.8659, 1.6733],
        [0.9804, 0.3964, 1.2190],
        [1.5406, 0.7431, 1.4739],
        [1.7596, 1.1239, 0.8174]])


In [19]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.3148, 0.8792, 1.3479],
        [0.9619, 1.8659, 1.6733],
        [0.9804, 0.3964, 1.2190],
        [1.5406, 0.7431, 1.4739],
        [1.7596, 1.1239, 0.8174]])


In [20]:
print(y.add_(x))

tensor([[1.3148, 0.8792, 1.3479],
        [0.9619, 1.8659, 1.6733],
        [0.9804, 0.3964, 1.2190],
        [1.5406, 0.7431, 1.4739],
        [1.7596, 1.1239, 0.8174]])


In [22]:
print(y[:1])

tensor([[1.3148, 0.8792, 1.3479]])


In [25]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [26]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.3203])
-1.3202680349349976


In [27]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [28]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [29]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [31]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)

print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [39]:
if torch.cuda.is_available:
  device = torch.device('cuda')
  y = torch.ones_like(x, device=device)
  x =x.to(device)
  
  z = x + y

  print(z)
  print(z.to('cpu', torch.double))

tensor([2.], device='cuda:0')
tensor([2.], dtype=torch.float64)
