<a href="https://colab.research.google.com/github/EmiHamada/Sunb_Box/blob/master/Pytourch/tutorial/PyTourch_tutorial_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Deep Learning with PyTorch: A 60 Minute Blitz_AUTOGRAD: AUTOMATIC DIFFERENTIATION   
 [PyTourch公式](
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html)

## 必要なライブラリの読み込み

In [0]:
import torch

## コード実行していく

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [8]:
a = torch.randn(2, 2)
a = ((a * 3)/(a - 1))
print(a.requires_grad_(True))
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([[  1.4036,   0.7111],
        [  0.8500, 167.1146]], requires_grad=True)
True


In [0]:
out.backward()

In [12]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [21]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([-1494.6914,   762.8595,   -35.2663], grad_fn=<MulBackward0>)


In [22]:
v =torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [24]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False
